//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MvcBootstrap.OracleEFModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBEntity : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBEntity object using the connection string found in the 'DBEntity' section of the application configuration file.
        /// </summary>
        public DBEntity() : base("name=DBEntity", "DBEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntity object.
        /// </summary>
        public DBEntity(string connectionString) : base(connectionString, "DBEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntity object.
        /// </summary>
        public DBEntity(EntityConnection connection) : base(connection, "DBEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_AisCategory> T_AisCategory
        {
            get
            {
                if ((_T_AisCategory == null))
                {
                    _T_AisCategory = base.CreateObjectSet<T_AisCategory>("T_AisCategory");
                }
                return _T_AisCategory;
            }
        }
        private ObjectSet<T_AisCategory> _T_AisCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_AisResource> T_AisResource
        {
            get
            {
                if ((_T_AisResource == null))
                {
                    _T_AisResource = base.CreateObjectSet<T_AisResource>("T_AisResource");
                }
                return _T_AisResource;
            }
        }
        private ObjectSet<T_AisResource> _T_AisResource;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Log> T_Log
        {
            get
            {
                if ((_T_Log == null))
                {
                    _T_Log = base.CreateObjectSet<T_Log>("T_Log");
                }
                return _T_Log;
            }
        }
        private ObjectSet<T_Log> _T_Log;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Module> T_Module
        {
            get
            {
                if ((_T_Module == null))
                {
                    _T_Module = base.CreateObjectSet<T_Module>("T_Module");
                }
                return _T_Module;
            }
        }
        private ObjectSet<T_Module> _T_Module;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Operation> T_Operation
        {
            get
            {
                if ((_T_Operation == null))
                {
                    _T_Operation = base.CreateObjectSet<T_Operation>("T_Operation");
                }
                return _T_Operation;
            }
        }
        private ObjectSet<T_Operation> _T_Operation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Permission> T_Permission
        {
            get
            {
                if ((_T_Permission == null))
                {
                    _T_Permission = base.CreateObjectSet<T_Permission>("T_Permission");
                }
                return _T_Permission;
            }
        }
        private ObjectSet<T_Permission> _T_Permission;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Role> T_Role
        {
            get
            {
                if ((_T_Role == null))
                {
                    _T_Role = base.CreateObjectSet<T_Role>("T_Role");
                }
                return _T_Role;
            }
        }
        private ObjectSet<T_Role> _T_Role;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_User> T_User
        {
            get
            {
                if ((_T_User == null))
                {
                    _T_User = base.CreateObjectSet<T_User>("T_User");
                }
                return _T_User;
            }
        }
        private ObjectSet<T_User> _T_User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_UserNode> T_UserNode
        {
            get
            {
                if ((_T_UserNode == null))
                {
                    _T_UserNode = base.CreateObjectSet<T_UserNode>("T_UserNode");
                }
                return _T_UserNode;
            }
        }
        private ObjectSet<T_UserNode> _T_UserNode;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_UserRole> T_UserRole
        {
            get
            {
                if ((_T_UserRole == null))
                {
                    _T_UserRole = base.CreateObjectSet<T_UserRole>("T_UserRole");
                }
                return _T_UserRole;
            }
        }
        private ObjectSet<T_UserRole> _T_UserRole;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_AisCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_AisCategory(T_AisCategory t_AisCategory)
        {
            base.AddObject("T_AisCategory", t_AisCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_AisResource EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_AisResource(T_AisResource t_AisResource)
        {
            base.AddObject("T_AisResource", t_AisResource);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Log(T_Log t_Log)
        {
            base.AddObject("T_Log", t_Log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Module EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Module(T_Module t_Module)
        {
            base.AddObject("T_Module", t_Module);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Operation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Operation(T_Operation t_Operation)
        {
            base.AddObject("T_Operation", t_Operation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Permission EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Permission(T_Permission t_Permission)
        {
            base.AddObject("T_Permission", t_Permission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Role EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Role(T_Role t_Role)
        {
            base.AddObject("T_Role", t_Role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_User(T_User t_User)
        {
            base.AddObject("T_User", t_User);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_UserNode EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_UserNode(T_UserNode t_UserNode)
        {
            base.AddObject("T_UserNode", t_UserNode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_UserRole EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_UserRole(T_UserRole t_UserRole)
        {
            base.AddObject("T_UserRole", t_UserRole);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_AisCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_AisCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_AisCategory object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_AisCategory CreateT_AisCategory(global::System.Int32 id)
        {
            T_AisCategory t_AisCategory = new T_AisCategory();
            t_AisCategory.ID = id;
            return t_AisCategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int32> value);
        partial void OnParentIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_AisResource")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_AisResource : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_AisResource object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_AisResource CreateT_AisResource(global::System.String id)
        {
            T_AisResource t_AisResource = new T_AisResource();
            t_AisResource.ID = id;
            return t_AisResource;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResourceName
        {
            get
            {
                return _ResourceName;
            }
            set
            {
                OnResourceNameChanging(value);
                ReportPropertyChanging("ResourceName");
                _ResourceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResourceName");
                OnResourceNameChanged();
            }
        }
        private global::System.String _ResourceName;
        partial void OnResourceNameChanging(global::System.String value);
        partial void OnResourceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ResourceContent
        {
            get
            {
                return StructuralObject.GetValidValue(_ResourceContent);
            }
            set
            {
                OnResourceContentChanging(value);
                ReportPropertyChanging("ResourceContent");
                _ResourceContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResourceContent");
                OnResourceContentChanged();
            }
        }
        private global::System.Byte[] _ResourceContent;
        partial void OnResourceContentChanging(global::System.Byte[] value);
        partial void OnResourceContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ResourceVersion
        {
            get
            {
                return _ResourceVersion;
            }
            set
            {
                OnResourceVersionChanging(value);
                ReportPropertyChanging("ResourceVersion");
                _ResourceVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResourceVersion");
                OnResourceVersionChanged();
            }
        }
        private Nullable<global::System.Decimal> _ResourceVersion;
        partial void OnResourceVersionChanging(Nullable<global::System.Decimal> value);
        partial void OnResourceVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int32> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResourcePath
        {
            get
            {
                return _ResourcePath;
            }
            set
            {
                OnResourcePathChanging(value);
                ReportPropertyChanging("ResourcePath");
                _ResourcePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResourcePath");
                OnResourcePathChanged();
            }
        }
        private global::System.String _ResourcePath;
        partial void OnResourcePathChanging(global::System.String value);
        partial void OnResourcePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResourceDetail
        {
            get
            {
                return _ResourceDetail;
            }
            set
            {
                OnResourceDetailChanging(value);
                ReportPropertyChanging("ResourceDetail");
                _ResourceDetail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResourceDetail");
                OnResourceDetailChanged();
            }
        }
        private global::System.String _ResourceDetail;
        partial void OnResourceDetailChanging(global::System.String value);
        partial void OnResourceDetailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Log object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_Log CreateT_Log(global::System.Int32 id)
        {
            T_Log t_Log = new T_Log();
            t_Log.ID = id;
            return t_Log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IpAddress
        {
            get
            {
                return _IpAddress;
            }
            set
            {
                OnIpAddressChanging(value);
                ReportPropertyChanging("IpAddress");
                _IpAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IpAddress");
                OnIpAddressChanged();
            }
        }
        private global::System.String _IpAddress;
        partial void OnIpAddressChanging(global::System.String value);
        partial void OnIpAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Controller
        {
            get
            {
                return _Controller;
            }
            set
            {
                OnControllerChanging(value);
                ReportPropertyChanging("Controller");
                _Controller = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Controller");
                OnControllerChanged();
            }
        }
        private global::System.String _Controller;
        partial void OnControllerChanging(global::System.String value);
        partial void OnControllerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Module object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_Module CreateT_Module(global::System.Int32 id)
        {
            T_Module t_Module = new T_Module();
            t_Module.ID = id;
            return t_Module;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Controller
        {
            get
            {
                return _Controller;
            }
            set
            {
                OnControllerChanging(value);
                ReportPropertyChanging("Controller");
                _Controller = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Controller");
                OnControllerChanged();
            }
        }
        private global::System.String _Controller;
        partial void OnControllerChanging(global::System.String value);
        partial void OnControllerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int32> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Int16> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Int16> value);
        partial void OnIsEnableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Operations
        {
            get
            {
                return _Operations;
            }
            set
            {
                OnOperationsChanging(value);
                ReportPropertyChanging("Operations");
                _Operations = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Operations");
                OnOperationsChanged();
            }
        }
        private global::System.String _Operations;
        partial void OnOperationsChanging(global::System.String value);
        partial void OnOperationsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_Operation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Operation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Operation object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_Operation CreateT_Operation(global::System.Int32 id)
        {
            T_Operation t_Operation = new T_Operation();
            t_Operation.ID = id;
            return t_Operation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreateUserId
        {
            get
            {
                return _CreateUserId;
            }
            set
            {
                OnCreateUserIdChanging(value);
                ReportPropertyChanging("CreateUserId");
                _CreateUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUserId");
                OnCreateUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreateUserId;
        partial void OnCreateUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreateUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_Permission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Permission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Permission object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_Permission CreateT_Permission(global::System.Int32 id)
        {
            T_Permission t_Permission = new T_Permission();
            t_Permission.ID = id;
            return t_Permission;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleID;
        partial void OnRoleIDChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ControllerID
        {
            get
            {
                return _ControllerID;
            }
            set
            {
                OnControllerIDChanging(value);
                ReportPropertyChanging("ControllerID");
                _ControllerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ControllerID");
                OnControllerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ControllerID;
        partial void OnControllerIDChanging(Nullable<global::System.Int32> value);
        partial void OnControllerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ActionID
        {
            get
            {
                return _ActionID;
            }
            set
            {
                OnActionIDChanging(value);
                ReportPropertyChanging("ActionID");
                _ActionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionID");
                OnActionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ActionID;
        partial void OnActionIDChanging(Nullable<global::System.Int32> value);
        partial void OnActionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreateUserID
        {
            get
            {
                return _CreateUserID;
            }
            set
            {
                OnCreateUserIDChanging(value);
                ReportPropertyChanging("CreateUserID");
                _CreateUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUserID");
                OnCreateUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CreateUserID;
        partial void OnCreateUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnCreateUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifyUserID
        {
            get
            {
                return _ModifyUserID;
            }
            set
            {
                OnModifyUserIDChanging(value);
                ReportPropertyChanging("ModifyUserID");
                _ModifyUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyUserID");
                OnModifyUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifyUserID;
        partial void OnModifyUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnModifyUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifyDate
        {
            get
            {
                return _ModifyDate;
            }
            set
            {
                OnModifyDateChanging(value);
                ReportPropertyChanging("ModifyDate");
                _ModifyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyDate");
                OnModifyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifyDate;
        partial void OnModifyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifyDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Role object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_Role CreateT_Role(global::System.Int32 id)
        {
            T_Role t_Role = new T_Role();
            t_Role.ID = id;
            return t_Role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IsEnable
        {
            get
            {
                return _IsEnable;
            }
            set
            {
                OnIsEnableChanging(value);
                ReportPropertyChanging("IsEnable");
                _IsEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnable");
                OnIsEnableChanged();
            }
        }
        private Nullable<global::System.Int16> _IsEnable;
        partial void OnIsEnableChanging(Nullable<global::System.Int16> value);
        partial void OnIsEnableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreateUserID
        {
            get
            {
                return _CreateUserID;
            }
            set
            {
                OnCreateUserIDChanging(value);
                ReportPropertyChanging("CreateUserID");
                _CreateUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUserID");
                OnCreateUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CreateUserID;
        partial void OnCreateUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnCreateUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifyUserID
        {
            get
            {
                return _ModifyUserID;
            }
            set
            {
                OnModifyUserIDChanging(value);
                ReportPropertyChanging("ModifyUserID");
                _ModifyUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyUserID");
                OnModifyUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifyUserID;
        partial void OnModifyUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnModifyUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifyUserDate
        {
            get
            {
                return _ModifyUserDate;
            }
            set
            {
                OnModifyUserDateChanging(value);
                ReportPropertyChanging("ModifyUserDate");
                _ModifyUserDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyUserDate");
                OnModifyUserDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifyUserDate;
        partial void OnModifyUserDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifyUserDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_User CreateT_User(global::System.Int32 id)
        {
            T_User t_User = new T_User();
            t_User.ID = id;
            return t_User;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RealName
        {
            get
            {
                return _RealName;
            }
            set
            {
                OnRealNameChanging(value);
                ReportPropertyChanging("RealName");
                _RealName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RealName");
                OnRealNameChanged();
            }
        }
        private global::System.String _RealName;
        partial void OnRealNameChanging(global::System.String value);
        partial void OnRealNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IsLocked
        {
            get
            {
                return _IsLocked;
            }
            set
            {
                OnIsLockedChanging(value);
                ReportPropertyChanging("IsLocked");
                _IsLocked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLocked");
                OnIsLockedChanged();
            }
        }
        private Nullable<global::System.Int16> _IsLocked;
        partial void OnIsLockedChanging(Nullable<global::System.Int16> value);
        partial void OnIsLockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginTime
        {
            get
            {
                return _LastLoginTime;
            }
            set
            {
                OnLastLoginTimeChanging(value);
                ReportPropertyChanging("LastLoginTime");
                _LastLoginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginTime");
                OnLastLoginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginTime;
        partial void OnLastLoginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreateUserID
        {
            get
            {
                return _CreateUserID;
            }
            set
            {
                OnCreateUserIDChanging(value);
                ReportPropertyChanging("CreateUserID");
                _CreateUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUserID");
                OnCreateUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CreateUserID;
        partial void OnCreateUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnCreateUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifyUserID
        {
            get
            {
                return _ModifyUserID;
            }
            set
            {
                OnModifyUserIDChanging(value);
                ReportPropertyChanging("ModifyUserID");
                _ModifyUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyUserID");
                OnModifyUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifyUserID;
        partial void OnModifyUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnModifyUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifyDate
        {
            get
            {
                return _ModifyDate;
            }
            set
            {
                OnModifyDateChanging(value);
                ReportPropertyChanging("ModifyDate");
                _ModifyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifyDate");
                OnModifyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifyDate;
        partial void OnModifyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_UserNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_UserNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_UserNode object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static T_UserNode CreateT_UserNode(global::System.Int32 userID)
        {
            T_UserNode t_UserNode = new T_UserNode();
            t_UserNode.UserID = userID;
            return t_UserNode;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AisCategoryID
        {
            get
            {
                return _AisCategoryID;
            }
            set
            {
                OnAisCategoryIDChanging(value);
                ReportPropertyChanging("AisCategoryID");
                _AisCategoryID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AisCategoryID");
                OnAisCategoryIDChanged();
            }
        }
        private global::System.String _AisCategoryID;
        partial void OnAisCategoryIDChanging(global::System.String value);
        partial void OnAisCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AisResourceCacheID
        {
            get
            {
                return _AisResourceCacheID;
            }
            set
            {
                OnAisResourceCacheIDChanging(value);
                ReportPropertyChanging("AisResourceCacheID");
                _AisResourceCacheID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AisResourceCacheID");
                OnAisResourceCacheIDChanged();
            }
        }
        private global::System.String _AisResourceCacheID;
        partial void OnAisResourceCacheIDChanging(global::System.String value);
        partial void OnAisResourceCacheIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EFModel", Name="T_UserRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_UserRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_UserRole object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        public static T_UserRole CreateT_UserRole(global::System.Int32 userID, global::System.Int32 roleID)
        {
            T_UserRole t_UserRole = new T_UserRole();
            t_UserRole.UserID = userID;
            t_UserRole.RoleID = roleID;
            return t_UserRole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();

        #endregion

    
    }

    #endregion

    
}
